name: Build Static Binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add --no-cache build-base fuse-dev

    - name: Build static binary
      run: make clean all LDFLAGS="-static"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mirrorfs-static
        path: mirrorfs
